import { Component } from '@angular/core';

@Component({
  selector: 'app-tab1',
  templateUrl: 'tab1.page.html',
  styleUrls: ['tab1.page.scss']
})
export class Tab1Page {

  constructor() {}
  contenido_noticia1="El Mundial de League of Legends 2024 ha comenzado con una intensidad inigualable, reuniendo a los mejores equipos del mundo en la competencia más esperada del año. Equipos de las principales regiones, como Corea del Sur, China, Europa y América del Norte, se enfrentan en batallas que prometen dejar huella en la historia del juego. En los primeros días del torneo, ya se han vivido momentos sorprendentes. El equipo favorito, T1, liderado por el legendario jugador Faker, tuvo una actuación sobresaliente en su primer encuentro, demostrando que siguen siendo un rival temido a pesar de la presión constante. Sin embargo, la sorpresa de la jornada la dio el equipo G2 Esports, que logró una victoria inesperada contra JDG Gaming, uno de los contendientes más fuertes de China.Los fanáticos han mostrado su entusiasmo, llenando estadios y generando un ambiente eléctrico tanto en los eventos presenciales como en las transmisiones en línea, donde se superaron cifras récord de audiencia. La nueva modalidad de eliminación directa ha generado polémica, pero también ha intensificado la emoción, haciendo que cada partida sea crucial para el destino de los equipos.Con la fase de grupos en pleno desarrollo, los analistas ya comienzan a predecir posibles sorpresas y eliminaciones tempranas de algunos de los gigantes de la competición. ";
  foto_lolo="https://cdn1.epicgames.com/offer/24b9b5e323bc40eea252a10cdd3b2f10/EGS_LeagueofLegends_RiotGames_S1_2560x1440-80471666c140f790f28dff68d72c384b";
  contenido_noticia2="El esperado EA SPORTS FC 25 debutó el 27 de septiembre de 2024, consolidando su posición como uno de los juegos de fútbol más auténticos. EA ha apostado fuerte por su innovadora tecnología HyperMotionV y la inteligencia artificial FC IQ, las cuales proporcionan una experiencia de juego más táctica y realista. Los jugadores ahora son más inteligentes, con roles y movimientos definidos por sus habilidades específicas, lo que añade una capa de estrategia a cada partido.Otro gran avance es la inclusión de las ligas femeninas en el modo Carrera, ofreciendo igualdad de opciones para los fanáticos del fútbol femenino. Esta actualización también incluye la UEFA Women’s Champions League y ligas como la Barclays Women's Super League y la Liga F, marcando un hito importante en la representación del fútbol femenino en videojuegos.En cuanto a la ambientación, EA SPORTS FC 25 presenta más de 120 estadios reales, incluyendo icónicos recintos como el Santiago Bernabéu y el Estadio José Alvalade, brindando una experiencia de día de partido inmersiva y auténtica.Con estas mejoras y la inclusión de nuevos ICONS y Héroes en el modo Ultimate Team, FC 25 promete ser el juego de fútbol más completo y emocionante hasta la fecha."
  foto_fifa="https://assets.nintendo.com/image/upload/ar_16:9,c_lpad,w_1240/b_white/f_auto/q_auto/ncom/software/switch/70010000074799/ab3989c5c208683e007deb3327a1ce70a8fa6cb38b06cfb8c2c80d563b19cfc7";
  contenido_noticia3="La temporada de F1 2024 ha comenzado con gran emoción tras la primera carrera en el Gran Premio de Bahréin, que dejó a los fanáticos del automovilismo con la promesa de una campaña llena de sorpresas y giros inesperados. Aunque los favoritos tradicionales como Max Verstappen y Lewis Hamilton se presentaban como los principales contendientes para el título, las primeras vueltas del campeonato han revelado que las fuerzas podrían estar cambiando.Sin embargo, no todo fue alegría para los favoritos. El bicampeón defensor, Max Verstappen de Red Bull, tuvo una jornada difícil tras sufrir problemas mecánicos en las últimas vueltas que lo dejaron fuera del podio, terminando en un amargo cuarto lugar. Red Bull sigue siendo fuerte, pero esta primera carrera demostró que tendrán que ajustar algunos aspectos si quieren mantener su dominio.Otra gran sorpresa fue el rendimiento del equipo Aston Martin. Fernando Alonso, a sus 42 años, sigue demostrando por qué es uno de los pilotos más talentosos de la parrilla, logrando un sorprendente segundo lugar, con una actuación que dejó a todos boquiabiertos. "  
  fotos_overwatch="https://media.contentapi.ea.com/content/dam/ea/f1/f1-24/common/f124-featured-image-16x9.jpg.adapt.crop16x9.575p.jpg";
  contenido_noticia4="El Valorant Champions 2024 ha comenzado con toda la emoción que caracteriza al torneo más prestigioso del shooter táctico de Riot Games. Este año, los mejores equipos de todo el mundo se han reunido para competir por el codiciado título de campeón, y los primeros enfrentamientos ya han dejado a los fanáticos al borde de sus asientos.Entre los grandes favoritos, LOUD y Fnatic han demostrado por qué llegaron con grandes expectativas, dominando a sus oponentes en las primeras jornadas. Sin embargo, la verdadera sorpresa del torneo hasta ahora ha sido el equipo Paper Rex, que ha logrado vencer a 100 Thieves en una partida que muchos consideraban una ventaja clara para el equipo norteamericano. Jinggg, la estrella de Paper Rex, ha sido clave en la victoria, destacándose por su precisión y agresividad con el nuevo agente Iso, recientemente añadido al juego.Hablando de Iso, su impacto en el meta ha sido significativo. ";
  foto_valorant="https://esportsbureau.com/wp-content/uploads/2020/04/valorant.jpg";
  contido_noticia5="En octubre de 2024, Red Dead Redemption 2 sigue dando de qué hablar con interesantes novedades. Rockstar lanzó un nuevo evento de Halloween para Red Dead Online, donde los jugadores deben enfrentarse a hordas de enemigos en el evento “All Hallow’s Call to Arms”. También se han añadido misiones especiales de telegrama y se ofrecen bonificaciones de XP, oro y dinero dentro del juego.Por otro lado, una posible actualización para las consolas de nueva generación ha sido objeto de rumores. Se especula sobre mejoras gráficas para PlayStation 5 y Xbox Series X, aunque todavía no hay confirmación oficial de Rockstar sobre el lanzamiento​.​";
  foto_rd2="https://cdn1.epicgames.com/b30b6d1b4dfd4dcc93b5490be5e094e5/offer/RDR2476298253_Epic_Games_Wishlist_RDR2_2560x1440_V01-2560x1440-2a9ebe1f7ee202102555be202d5632ec.jpg";
  contenido_noticia6="Una de las últimas noticias sobre God of War Ragnarök es que su esperada expansión, el DLC Valhalla, se lanzará el 12 de diciembre de 2023. En este contenido adicional, Kratos enfrentará nuevos desafíos en un entorno de tipo roguelite, donde deberá adaptarse y mejorar tras cada intento fallido, ya que cada derrota lo llevará de vuelta a las puertas del Valhalla para intentarlo nuevamente. Además, contará con cinco niveles de dificultad que puedes ajustar libremente entre intentos.En cuanto a la versión para PC, la adaptación de God of War Ragnarök ha recibido mejoras importantes, como soporte para resoluciones 4K, pantallas ultrawide y tecnologías de escalado como NVIDIA DLSS. Los gráficos son impresionantes, y el rendimiento ha sido sólido, con la posibilidad de jugar a 60 FPS en equipos con componentes de gama alta";
  foto_ragnarock="https://cdn1.epicgames.com/spt-assets/edaff839f0734d16bc89d2ddb1dc9339/steel-magnolia-15owu.jpg";
  contenido_noticia7="Assassin's Creed Unity ha vuelto a captar la atención en 2024, a casi diez años de su lanzamiento. Uno de los momentos más destacados fue su aparición en la ceremonia de apertura de los Juegos Olímpicos de París, que rindió homenaje a este título ambientado en la Revolución Francesa. Este guiño se debe a la conexión de la saga con la historia y cultura francesa, lo que llevó a incluir elementos visuales que evocaban el juego durante la ceremonia.Además, muchos jugadores han redescubierto Unity y han valorado sus impresionantes animaciones de parkour y combate, elementos que en su lanzamiento no fueron tan apreciados debido a los problemas técnicos que enfrentaba el juego. Hoy, gracias a parches y mejoras posteriores, es considerado una de las entregas más inmersivas de la serie."
  foton_unity="https://image.api.playstation.com/cdn/UP0001/CUSA00663_00/arnlFWX6Y6ZlGyCCYWmth94Shtw44kON.png";
  contenido_noticia8="Una gran noticia para los fans de Blasphemous 2: el 31 de octubre de 2024 se lanzará el primer DLC llamado Mea Culpa. Esta expansión se centra en la icónica espada Mea Culpa de la primera entrega, e incluirá dos nuevas zonas, jefes adicionales y misiones inéditas. Además, habrá una nueva arma, rezos, NPCs, cuentas de rosario y logros para descubrir​.El mismo día, también se lanzará una actualización gratuita llamada True Torment, que traerá el modo New Game+, nuevos desafíos, zonas expandidas y más enemigos, garantizando aún más horas de contenido para los seguidores​.Este contenido estará disponible en todas las plataformas donde está Blasphemous 2: Xbox, PlayStation, Nintendo Switch y PC."
  foto_blb="https://store-images.s-microsoft.com/image/apps.54518.14467989922179877.1ceb8db6-3d8d-4caa-a83f-7ddb65f43744.1570e626-3e1a-4b2e-bfbe-b5a97e034f0f?q=90&w=480&h=270"
  contenido_noticia9="En 2024, Call of Duty: Black Ops 3 sigue siendo un juego popular, pero enfrenta riesgos de seguridad graves, especialmente en PC. Los hackers han explotado vulnerabilidades en el juego, lo que ha permitido ataques de ejecución remota de código (RCE) y la filtración de direcciones IP de los jugadores. Aunque Activision ha lanzado algunos parches, muchos problemas persisten. La comunidad ha desarrollado soluciones alternativas, como el cliente Plutonium y el parche T7, para mejorar la seguridad, aunque con riesgos de infracciones a los términos del juego,";
  foto_bo3="https://store-images.s-microsoft.com/image/apps.24461.66777443557046310.abf0f423-a960-4f91-982f-7c0e898cf325.6577cc39-16b4-4a2e-9981-368c1d0065cd?q=90&w=480&h=270";
  contenido_noticia10="En el mundo de Rainbow Six: Siege, una de las últimas novedades es la incorporación de 10 nuevos conjuntos de skins para equipos de esports. A través del programa R6 Share, los jugadores pueden apoyar a organizaciones profesionales de esports, como Dplus Kia, Falcons, Furia y M80, adquiriendo estos paquetes de cosméticos. El 50% de las ganancias va directamente a los equipos, ayudando a financiar su participación en competiciones​.Además, en términos de jugabilidad, se ha lanzado el Operador Skopós, un nuevo personaje introducido en septiembre de 2024 con habilidades únicas​(Ubisoft. También ha habido ajustes importantes en la jugabilidad, como actualizaciones en los mapas Stadium Alpha y Bravo, mejorando el equilibrio del juego al eliminar el vidrio a prueba de balas de ciertos sitios de objetivos"
  foto_r6="https://staticctf.ubisoft.com/J3yJr34U2pZ2Ieem48Dwy9uqj5PNUQTn/4IZecJyhvcIUxxu0Rd1vjX/b9fb7577b74b56704d3d2b34be639397/R6S_Y7_KEYART_STANDARD.jpg";
  contenido_noticia11="La noticia más reciente sobre Blasphemous 2 es el lanzamiento del DLC Mea Culpa el 31 de octubre de 2024. Este contenido descargable introduce dos nuevas zonas, jefes adicionales, misiones inéditas y, como novedad, la legendaria espada Mea Culpa del primer juego. Además, se incluirán nuevos NPCs, una nueva arma, y varias mejoras, como rezos y logros.Ese mismo día, también llegará una actualización gratuita llamada True Torment, que incluye el modo New Game+ y expansiones en las zonas actuales, ofreciendo más desafíos y enemigos para enriquecer la experiencia de juego"
  foto_blb2="https://image.api.playstation.com/vulcan/ap/rnd/202307/2609/5b7d787deb993232e95a008bed7081f9a824049554ad1bc4.png"
  contenido_noticia12="Recientemente, Elden Ring lanzó una nueva actualización, la versión 1.15, que introduce diversas mejoras de rendimiento y correcciones de errores, especialmente para los usuarios de PC y PlayStation. Esta actualización es parte de un esfuerzo continuo para optimizar el juego y solucionar problemas como velocidades de fotogramas inestables en PC, que pueden ser causadas por aplicaciones de terceros que afectan el mouse. Para los usuarios de PlayStation 5, se sugiere utilizar la opción Reconstruir base de datos en modo seguro para mejorar el rendimiento​.Entre las correcciones específicas, se han solucionado errores relacionados con armas como el Golem Fist y el hechizo Aspectos del Crisol, además de mejorar el comportamiento de algunos enemigos​.Esta actualización llega justo después del lanzamiento del DLC Shadow of the Erdtree, que ha tenido un gran éxito y es considerado probablemente la última expansión importante para el juego​."
  foto_elden="https://image.api.playstation.com/vulcan/ap/rnd/202107/1612/Y5RHNmzAtc6sRYwZlYiKHAxN.png";
}

