import { Component } from '@angular/core';

@Component({
  selector: 'app-tab1',
  templateUrl: 'tab1.page.html',
  styleUrls: ['tab1.page.scss']
})
export class Tab1Page {

  constructor() {}
  contenido_noticia1="El Mundial de League of Legends 2024 ha comenzado con una intensidad inigualable, reuniendo a los mejores equipos del mundo en la competencia más esperada del año. Equipos de las principales regiones, como Corea del Sur, China, Europa y América del Norte, se enfrentan en batallas que prometen dejar huella en la historia del juego. En los primeros días del torneo, ya se han vivido momentos sorprendentes. El equipo favorito, T1, liderado por el legendario jugador Faker, tuvo una actuación sobresaliente en su primer encuentro, demostrando que siguen siendo un rival temido a pesar de la presión constante. Sin embargo, la sorpresa de la jornada la dio el equipo G2 Esports, que logró una victoria inesperada contra JDG Gaming, uno de los contendientes más fuertes de China.Los fanáticos han mostrado su entusiasmo, llenando estadios y generando un ambiente eléctrico tanto en los eventos presenciales como en las transmisiones en línea, donde se superaron cifras récord de audiencia. La nueva modalidad de eliminación directa ha generado polémica, pero también ha intensificado la emoción, haciendo que cada partida sea crucial para el destino de los equipos.Con la fase de grupos en pleno desarrollo, los analistas ya comienzan a predecir posibles sorpresas y eliminaciones tempranas de algunos de los gigantes de la competición. Se espera que los equipos de China y Corea del Sur continúen dominando, pero con el nivel actual de competencia, es difícil predecir qué sucederá a continuación.El Mundial de League of Legends 2024 promete continuar brindando momentos épicos, y los fanáticos de todo el mundo se mantienen expectantes de ver quién se coronará como el campeón de esta edición.";
  foto_lolo="https://cdn1.epicgames.com/offer/24b9b5e323bc40eea252a10cdd3b2f10/EGS_LeagueofLegends_RiotGames_S1_2560x1440-80471666c140f790f28dff68d72c384b";
  contenido_noticia2="El esperado EA SPORTS FC 25 debutó el 27 de septiembre de 2024, consolidando su posición como uno de los juegos de fútbol más auténticos. EA ha apostado fuerte por su innovadora tecnología HyperMotionV y la inteligencia artificial FC IQ, las cuales proporcionan una experiencia de juego más táctica y realista. Los jugadores ahora son más inteligentes, con roles y movimientos definidos por sus habilidades específicas, lo que añade una capa de estrategia a cada partido.Otro gran avance es la inclusión de las ligas femeninas en el modo Carrera, ofreciendo igualdad de opciones para los fanáticos del fútbol femenino. Esta actualización también incluye la UEFA Women’s Champions League y ligas como la Barclays Women's Super League y la Liga F, marcando un hito importante en la representación del fútbol femenino en videojuegos.En cuanto a la ambientación, EA SPORTS FC 25 presenta más de 120 estadios reales, incluyendo icónicos recintos como el Santiago Bernabéu y el Estadio José Alvalade, brindando una experiencia de día de partido inmersiva y auténtica.Con estas mejoras y la inclusión de nuevos ICONS y Héroes en el modo Ultimate Team, FC 25 promete ser el juego de fútbol más completo y emocionante hasta la fecha."
  foto_csgo="https://assets.nintendo.com/image/upload/ar_16:9,c_lpad,w_1240/b_white/f_auto/q_auto/ncom/software/switch/70010000074799/ab3989c5c208683e007deb3327a1ce70a8fa6cb38b06cfb8c2c80d563b19cfc7";
  contenido_noticia3="La temporada de F1 2024 ha comenzado con gran emoción tras la primera carrera en el Gran Premio de Bahréin, que dejó a los fanáticos del automovilismo con la promesa de una campaña llena de sorpresas y giros inesperados. Aunque los favoritos tradicionales como Max Verstappen y Lewis Hamilton se presentaban como los principales contendientes para el título, las primeras vueltas del campeonato han revelado que las fuerzas podrían estar cambiando.Sin embargo, no todo fue alegría para los favoritos. El bicampeón defensor, Max Verstappen de Red Bull, tuvo una jornada difícil tras sufrir problemas mecánicos en las últimas vueltas que lo dejaron fuera del podio, terminando en un amargo cuarto lugar. Red Bull sigue siendo fuerte, pero esta primera carrera demostró que tendrán que ajustar algunos aspectos si quieren mantener su dominio.Otra gran sorpresa fue el rendimiento del equipo Aston Martin. Fernando Alonso, a sus 42 años, sigue demostrando por qué es uno de los pilotos más talentosos de la parrilla, logrando un sorprendente segundo lugar, con una actuación que dejó a todos boquiabiertos. El coche de Aston Martin ha mostrado un rendimiento inesperado, colocándolos como posibles contendientes en las próximas carreras.La temporada de F1 2024 apenas comienza, pero ya promete ser una de las más emocionantes de los últimos años. Los equipos están más competitivos que nunca, y con nuevas reglas aerodinámicas y ajustes en los motores, todo está por decidirse en las próximas carreras. Los fanáticos de todo el mundo están ansiosos por ver qué sorpresas traerá el Gran Premio de Arabia Saudita, la próxima parada en el calendario."  
  fotos_overwatch="https://media.contentapi.ea.com/content/dam/ea/f1/f1-24/common/f124-featured-image-16x9.jpg.adapt.crop16x9.575p.jpg";
  contenido_noticia4="El Valorant Champions 2024 ha comenzado con toda la emoción que caracteriza al torneo más prestigioso del shooter táctico de Riot Games. Este año, los mejores equipos de todo el mundo se han reunido para competir por el codiciado título de campeón, y los primeros enfrentamientos ya han dejado a los fanáticos al borde de sus asientos.Entre los grandes favoritos, LOUD y Fnatic han demostrado por qué llegaron con grandes expectativas, dominando a sus oponentes en las primeras jornadas. Sin embargo, la verdadera sorpresa del torneo hasta ahora ha sido el equipo Paper Rex, que ha logrado vencer a 100 Thieves en una partida que muchos consideraban una ventaja clara para el equipo norteamericano. Jinggg, la estrella de Paper Rex, ha sido clave en la victoria, destacándose por su precisión y agresividad con el nuevo agente Iso, recientemente añadido al juego.Hablando de Iso, su impacto en el meta ha sido significativo. Este nuevo duelista ha aportado un estilo de juego más dinámico y agresivo, cambiando la forma en que muchos equipos abordan las partidas. En particular, DRX, el equipo surcoreano, ha demostrado un dominio impecable del personaje, utilizando su kit de habilidades para mantener el control en las rondas clave, lo que les permitió obtener una victoria crucial en su debut.Los cambios recientes en el equilibrio del juego y las actualizaciones en los mapas también han sido tema de conversación. El regreso de Split al competitivo ha generado debates, pero hasta ahora, algunos equipos han mostrado un dominio estratégico sobre el mapa, sacando partido de las nuevas modificaciones. Equipos como Team Liquid han explotado estos cambios a la perfección, con un juego que mezcla agresividad y control de área, logrando victorias importantes en los primeros días.La audiencia global de Valorant ha alcanzado cifras sin precedentes, con millones de espectadores sintonizando las transmisiones desde todo el mundo. Las redes sociales han estallado con momentos virales, destacando jugadas increíbles y enfrentamientos épicos, lo que refuerza el crecimiento meteórico de Valorant como uno de los principales esports del momento.Con la fase de grupos en pleno desarrollo, todavía es temprano para hacer predicciones definitivas, pero si algo está claro es que el Valorant Champions 2024 promete ser uno de los torneos más reñidos y emocionantes en la historia del juego. Los equipos tendrán que seguir adaptándose rápidamente al meta en constante evolución si quieren alzarse con la victoria y convertirse en los campeones mundiales de esta temporada.";
  foto_valorant="https://esportsbureau.com/wp-content/uploads/2020/04/valorant.jpg";
}
